# Generated by Django 4.0.6 on 2022-07-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_bathrooms',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_bedrooms',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='listing',
            name='square_footage',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='property', max_length=150),
        ),
    ]
